name: CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Data Repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/aws_data_eng_project
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/terraform-weather-pipeline-1808181f
          token: ${{ secrets.GH_TOKEN }}
          path: terraform

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/infra
        run: |
          terraform init -input=false

      - name: Build common layer
        run: |
          mkdir -p layer/python/common
          cp -r src/common/* layer/python/common/
          mkdir -p dist
          cd layer
          zip -r ../dist/common_layer.zip python

      - name: Upload common layer to S3
        run: |
          aws s3 cp dist/common_layer.zip s3://tfstate-weather-pipeline-olvsigpg/layer/common_layer.zip
          echo "✓ common layer uploaded to s3://tfstate-weather-pipeline-olvsigpg/layer/common_layer.zip"


      # ─── Lambda: stream_processor ────────────────────────────
      - name: Package & upload Lambda stream_processor
        run: |
          mkdir -p dist
          cd src/lambdas/stream_processor
          zip -r ../../../dist/stream_processor.zip . -x '__pycache__/*'
          cd ../../..
          aws s3 cp dist/stream_processor.zip s3://tfstate-weather-pipeline-olvsigpg/lambda/stream_processor.zip
          echo "✓ stream_processor uploaded to s3://tfstate-weather-pipeline-olvsigpg/lambda/stream_processor.zip"
      # ⚠ No Terraform output matched for stream_processor — uploaded to S3 only (no update-function-code).

      # ─── Lambda: weather_producer ────────────────────────────
      - name: Package & upload Lambda weather_producer
        run: |
          mkdir -p dist
          cd src/lambdas/weather_producer
          zip -r ../../../dist/weather_producer.zip . -x '__pycache__/*'
          cd ../../..
          aws s3 cp dist/weather_producer.zip s3://tfstate-weather-pipeline-olvsigpg/lambda/weather_producer.zip
          echo "✓ weather_producer uploaded to s3://tfstate-weather-pipeline-olvsigpg/lambda/weather_producer.zip"
      # ⚠ No Terraform output matched for weather_producer — uploaded to S3 only (no update-function-code).
