name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # ============================================
      # CHECKOUT TERRAFORM REPOSITORY
      # ============================================
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/terraform-e-coo-20e7001a
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      # ============================================
      # AWS CREDENTIALS
      # ============================================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ============================================
      # TERRAFORM
      # ============================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ============================================
      # DESTROY INFRA
      # ============================================
      - name: Terraform Init - Infra
        working-directory: infra
        run: terraform init

      - name: Terraform Destroy - Infra
        working-directory: infra
        run: terraform destroy -auto-approve

      # ============================================
      # DESTROY BOOTSTRAP
      # ============================================
      - name: Terraform Init - Bootstrap
        working-directory: bootstrap
        run: terraform init

      - name: Terraform Destroy - Bootstrap
        working-directory: bootstrap
        run: terraform destroy -auto-approve

      # ============================================
      # FINISH
      # ============================================
      - name: Destroy completed
        run: |
          echo "======================================"
          echo "Terraform destroy completed successfully"
          echo "======================================"
