name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true
        type: string

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == 'DESTROY'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: mohamedamine050/terraform-e-commerce-pipeline-0e2f10c6
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Destroy Infra
        working-directory: infra
        run: |
          terraform init
          terraform destroy -auto-approve

      - name: Destroy Bootstrap
        working-directory: bootstrap
        run: |
          terraform init
          terraform destroy -auto-approve
